export const JOB_ADD_REQUEST = "JOB_ADD_REQUEST";
export const JOB_ADD_SUCCESS = "JOB_ADD_SUCCESS";
export const JOB_ADD_FAIL = "JOB_ADD_FAIL";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";

export const JOB_UPDATE_REQUEST = "JOB_UPDATE_REQUEST";
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS";
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL";

export const JOB_GETBYSEARCH_REQUEST = "JOB_GETBYSEARCH_REQUEST";
export const JOB_GETBYSEARCH_SUCCESS = "JOB_GETBYSEARCH_SUCCESSS";
export const JOB_GETBYSEARCH_FAIL = "JOB_GETBYSEARCH_FAIL";

export const JOB_GET_ALL_REQUEST = "JOB_GET_ALL_REQUEST";
export const JOB_GET_ALL_SUCCESS = "JOB_GET_ALL_SUCCESS";
export const JOB_GET_ALL_FAIL = "JOB_GET_ALL_FAIL";
